### ISSUE TITLE
[ADD] Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by jayneeel** [CSI-DMCE-2023/Hacktober-TicTacToe-2023#4]
Create and add this file in repo

[CONTRIBUTING.md](https://github.com/CSI-DMCE-2023/CSI-API-HacktoberFest-2023/blob/main/CONTRIBUTING.md)

**Comment by aks057** [comment]
can you assign it to me?

**Comment by nexuspy** [comment]
can I work on this?

**Comment by RVB179** [comment]
can i get this?
